// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq7kc18t7W6KEgV6YEqlM07BpcXMlVX5g',
    appId: '1:386749704846:web:7576306f94e479e88e77df',
    messagingSenderId: '386749704846',
    projectId: 'food-app-flutter-57382',
    authDomain: 'food-app-flutter-57382.firebaseapp.com',
    storageBucket: 'food-app-flutter-57382.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIFURPskB6wmLPsn9BlrGM0i83djTof9c',
    appId: '1:386749704846:android:12a8c9c1f5ae7c3a8e77df',
    messagingSenderId: '386749704846',
    projectId: 'food-app-flutter-57382',
    storageBucket: 'food-app-flutter-57382.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq7kc18t7W6KEgV6YEqlM07BpcXMlVX5g',
    appId: '1:386749704846:web:6d2ef5973e4baf8e8e77df',
    messagingSenderId: '386749704846',
    projectId: 'food-app-flutter-57382',
    authDomain: 'food-app-flutter-57382.firebaseapp.com',
    storageBucket: 'food-app-flutter-57382.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDSBlNXP3t6qZIrykG2GQSAulS-ZDbxhw',
    appId: '1:386749704846:ios:7446811219569c968e77df',
    messagingSenderId: '386749704846',
    projectId: 'food-app-flutter-57382',
    storageBucket: 'food-app-flutter-57382.firebasestorage.app',
    iosClientId: '386749704846-kdll010qvfsb3dpgjp1li7661tvmkugr.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodAppFlutter',
  );

}